In [7]:
import torch

x = torch.empty(3) #1d vector with 3 elements initialized to 0
y = torch.rand(2,2) #2d vector with 2 columns randomaly intitialized
z = torch.empty(2,2, dtype=torch.int32) #integer
a = torch.tensor([2,3])
a[1].item() #returns 3 as number
a[1] # returns 3 as tensor

tensor(3)

In [9]:
# tensor to numpy
a.numpy()

array([2, 3])

In [11]:
b = torch.from_numpy(a.numpy()) #numpy to tensor

In [12]:
if torch.cuda.is_available():
  device = torch.device('cuda')
  x = torch.ones(5, device=device) #put tensor in the gpu
  y = torch.ones(5)
  y = y.to(device) #moves to gpu
  #performs calculations much faster

In [20]:
x = torch.randn(1,5, requires_grad=True) #means this requires gradient
print(x)
#whenever we do operations with this, pytorch will create a computational graph
y = x+2
print(y)

z = torch.mm(torch.t(x),y)
print(z)

z.sum().backward() #grad can only be created for scalar outputs
print(x.grad)

tensor([[ 0.5632,  0.7852, -0.3008, -0.2570, -0.5149]], requires_grad=True)
tensor([[2.5632, 2.7852, 1.6992, 1.7430, 1.4851]], grad_fn=<AddBackward0>)
tensor([[ 1.4435,  1.5685,  0.9569,  0.9816,  0.8363],
        [ 2.0127,  2.1871,  1.3343,  1.3687,  1.1662],
        [-0.7711, -0.8379, -0.5111, -0.5243, -0.4467],
        [-0.6587, -0.7158, -0.4367, -0.4479, -0.3816],
        [-1.3198, -1.4342, -0.8750, -0.8975, -0.7647]], grad_fn=<MmBackward0>)
tensor([[10.5514, 10.5514, 10.5514, 10.5514, 10.5514]])


In [21]:
#When we want to update weights that must not be part of gradient calculation
#So we can use the following functions to stop gradient calculation
# x.requires_grad_(False)
# x.detach()
# with torch.no_grad():

In [22]:
#Examples
weights = torch.ones(4, requires_grad=True)

for epoch in range(1):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)

  #before we do next iteration we have to empty the ccurrent gradients
  weights.grad.zero_()

tensor([3., 3., 3., 3.])
